### ISSUE TITLE
Coffee Bush Incompatibility with Create Mod Harvester

### ISSUE THREAD

**Issue by berttholio-create** [AmarokIce/CoffeeDelight#16]
#### **Mod Versions:**
- **CoffeeDelight Version:** 1.4 (Forge)  
- **Minecraft Version:** 1.20.1  
- **Create Mod Version:** 0.5.1j

---

#### **Issue Description:**
The **Coffee Bush** in CoffeeDelight cannot be harvested using the Create Mod's **Mechanical Harvester**. When the harvester interacts with the Coffee Bush:  
1. The bush is broken as expected.  
2. However, **no loot is dropped** (e.g., no coffee berries).  

---

#### **Expected Behavior:**
The Create Mod harvester should be able to collect loot from the Coffee Bush when it is harvested.

---

#### **Possible Cause:**
The Coffee Bush requires the **"Use" interaction** (e.g., right-click) to harvest properly, as manually breaking the bush also does not yield any loot. It seems the Mechanical Harvester is not triggering this "Use" functionality and is instead defaulting to the "breaking" behavior, which is incompatible with the loot mechanics of the Coffee Bush.

---

#### **Steps to Reproduce:**
1. Set up a Create Mod contraption with a Mechanical Harvester.  
2. Place fully grown Coffee Bushes along its harvesting path.  
3. Activate the contraption and observe the results:  
   - Bushes are broken.  
   - No items are dropped (e.g., coffee berries).  

#### **Additional Notes:**
- Similar crops like SweetBerries which I understand the CoffeeBush replicate in vanilla Minecraft work seamlessly with the Create Mod harvester.
-  I did see another mod did have issues with the harvester, but they did not PR or attach a commit to the issue on how they fixed it with their bush block. https://github.com/brnbrd/Delightful/issues/52

---

Thank you for your time and effort in maintaining and improving CoffeeDelight! Let me know if you need additional details or testing.

**Comment by AmarokIce** [comment]
I'll look into the solution, and thanks for the report
