### ISSUE TITLE
Item names are strange...

### ISSUE THREAD

**Issue by AnyankaT** [AmarokIce/CoffeeDelight#9]
Just a few suggestions for corrections for the item names in the English version...

The items should be a CUP of coffee - not a CAP - and a MUG of coffee - not a MAG.
Should be HANDLE not handel.
And should be a SLICE not a side.
GROUND COFFEE not coffee flour.
ROASTED coffee beans, not cooked.

Just to make it sound more like native English.

**Comment by AmarokIce** [comment]
Thanks!
